# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170911_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='channels',
        ),
        migrations.AlterField(
            model_name='destination',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'E-mail')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
