# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170912_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='file',
            field=models.FileField(default=-1, upload_to='destination_uploads'),
            preserve_default=False,
        ),
    ]
